spring.application.name=ECommerce

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/ECommerceDB
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=209715200
server.tomcat.max-swallow-size=-1
server.tomcat.max-part-count=200

#Server Configuration
spring.main.allow-bean-definition-overriding=true

#JWT Configuration
jwt.secret="eyCCDCTHIHheqxfouy23fhhn8n3xumop783492t5c609281x1r2kh10xhfe9fmx3g2348"
jwt.expiration=864000000

#Email Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=sayanmajumdar1920014@gmail.com
spring.mail.password=Sayan@2002
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Server Configuration
server.port=8080